### ISSUE TITLE
Error when trying to run normOffsets

### ISSUE THREAD

**Issue by sjquon** [LTLA/csaw#1]
csaw version 1.16.0

I am trying to run csaw, and when I get to the step to eliminate efficiency bias, I am encountering an error as seen below. 

My command: 
```
filtered.me<-normOffsets(filtered.me, se.out=T)
```
Error Message: 
```
Error in calcNormFactors.default(assay(object, i = assay.id, withDimnames = FALSE), : formal argument "lib.size" matched by multiple actual arguments

3. calcNormFactors(assay(object, i = assay.id, withDimnames = FALSE), lib.size = lib.sizes, doWeighting = weighted, ...)
2. normFactors(object, lib.size = lib.sizes, ..., assay.id = assay.id, se.out = se.out)
1. normOffsets(filtered.me, se.out = T, param = param)
```
I can't figure out why I am getting this error code and how to fix it. I've tried searching the error message but haven't come up with anything. I would be very grateful if you have any ideas on how I can solve this. 

I have attached a copy of my RMD file. 
[RStudio.pdf](https://github.com/LTLA/csaw/files/2700053/RStudio.pdf)

**Comment by LTLA** [comment]
Fixed in 1a7fbf89bfe67dc8dd5c96183f8ccd149714c279.
