### ISSUE TITLE
going defunct before removal?

### ISSUE THREAD

**Issue by hpages** [LTLA/csaw#10]
Hi Aaron,

commit 9fc9413756023969d2cfb26f755c6b6b1448b1b9

Have you considered making these functions defunct in BioC 3.11, before removing them in BioC 3.12? The advantage is that code using these things will fail with an error message that will hopefully be more useful than things like `Error: could not find function "filterWindows"` or `Error: object ‘filterWindows’ is not exported by 'namespace:csaw'` like here:

  https://bioconductor.org/checkResults/3.11/bioc-LATEST/icetea/malbec2-install.html

This is what we normally recommend. Yeah it also means that it takes 1 year to get rid of stuff we no longer want... A bummer! :-/

H.

**Comment by LTLA** [comment]
Yes, I guess I should.
