### ISSUE TITLE
Unit test failure on Mac arm64

### ISSUE THREAD

**Issue by hpages** [LTLA/csaw#21]
Very similar to https://github.com/LTLA/BiocNeighbors/issues/21.

Unit test failures ("Objects equal but not identical") on Mac arm64: https://bioconductor.org/checkResults/3.18/bioc-mac-arm64-LATEST/csaw/kjohnson1-checksrc.html

No Mac arm64 binary in BioC 3.18: https://bioconductor.org/packages/3.18/csaw

In this case the missing **csaw** binary is blocking propagation of Mac arm64 binaries for 7 Bioconductor packages in BioC 3.18.

Thanks,
H.

**Comment by LTLA** [comment]
Alright, let's see how it goes with 1.37.1.

**Comment by hpages** [comment]
Can you please push this to the RELEASE_3_18 branch? The goal is to produce a Mac arm64 binary for the BioC 3.18 release. Thanks!

**Comment by LTLA** [comment]
Done.

**Comment by hpages** [comment]
Thanks! Let see what happens on the next build report for kjohnson1 (should be tomorrow).

**Comment by hpages** [comment]
Thanks for fixing the unit tests on Mac arm64: https://bioconductor.org/checkResults/3.18/bioc-mac-arm64-LATEST/csaw/

Unfortunately the binary cannot propagate because of https://github.com/LTLA/metapod/issues/1

**Comment by hpages** [comment]
All good now. Thanks!
