### ISSUE TITLE
correlateReads/extractSE error: position vector should be 1-based

### ISSUE THREAD

**Issue by plbaldoni** [LTLA/csaw#6]
Hi,

I am getting the following error message under the new R version 3.6.0 when trying to run the `correlateReads` function from csaw 1.18.1:

```
> correlateReads(bamfile,param=readParam(discard=hg19.discard))
Error in .extractSE(bam.file, where = where, param = param) : 
  position vector should be 1-based
```

The function runs fine under the R version 3.5.2. Any solution for this?

Thank you very much,
Pedro Baldoni

**Comment by LTLA** [comment]
I would guess that you have some elements in `hg19.discard` that are starting from zero.

**Comment by plbaldoni** [comment]
Thanks Aaron, you're right.
