### ISSUE TITLE
annotation error

### ISSUE THREAD

**Issue by EllieDuan** [LTLA/csaw#7]
Hello,
   I had an error when running `detailRanges` in csaw using fly genome:

```

library(TxDb.Dmelanogaster.UCSC.dm6.ensGene)
library(org.Dm.eg.db)
anno <- detailRanges(rowRanges(filtered.data), orgdb=org.Dm.eg.db,
                     txdb=TxDb.Dmelanogaster.UCSC.dm6.ensGene)

```
Here is the message:
```
Error in .testForValidKeys(x, keys, keytype, fks) : 
  None of the keys entered are valid keys for 'ENTREZID'. Please use the keys method to see a listing of valid arguments.
```
Any suggestions?

Thank you very much!

Best,
Ellie

**Comment by LTLA** [comment]
I daresay that you need to fiddle with the `key.field=` and `name.field=` arguments. I assume that `TxDb.Dmelanogaster.UCSC.dm6.ensGene` uses ENSEMBL IDs as the keys, so perhaps `key.field="ENSEMBL"` would work.

**Comment by EllieDuan** [comment]
Yes! Thank you for your help!
