### ISSUE TITLE
 Downstream analysis of Csaw differential binding region

### ISSUE THREAD

**Issue by EllieDuan** [LTLA/csaw#9]
Hello,
Thank you for this great tool!
I have a question of downstream analysis after I got the differential binding (DB) region from Csaw tool, which used a window-based method. My questions are:

- Since it is not a peak involved method, do I overlap these DB region (window-clustered region) back to my MACS2 peaks?
- If I would like to know how protein-A peaks falls in to protein-B DB regions in WT compare to protein-A knockdown, can I directly overlap peaks to DB region? or you would recommend me to overlap peaks to peaks?

Thank you for your suggestions!
Best,
Ellie

**Comment by LTLA** [comment]
> * Since it is not a peak involved method, do I overlap these DB region (window-clustered region) back to my MACS2 peaks?

Why do you need to? 

> * If I would like to know how protein-A peaks falls in to protein-B DB regions in WT compare to protein-A knockdown, can I directly overlap peaks to DB region? or you would recommend me to overlap peaks to peaks?

I don't know what you're asking here.

**Comment by EllieDuan** [comment]
Thank you for the quick response! 
1. To overlap peaks with DB, I would like to check the consistency between peak calls and DB regions. I tried the pipelines of MACS2 and Csaw (pipeline pic link: [https://ibb.co/DwYsbnY](url)), now they are kind of disconnected, so I would like to bring them together. Do you recommend to use both in one analysis? or one or another?

2. Sorry about the confusion.  
I would like to study the interaction between two proteins, so we have ChIP-seq for each protein in WT condition vs. mRNA knockdown of each other. 

- For example, I first use csaw to determine protein-B's DB in WT vs. protein-A knockdown. Then, I would like to know the percentage of protein-A binds to the protein-B's DB and non-DB region, and how far away of distance between protein-A binding sites to protein-B's DB.  
- Therefore, I will need to overlap protein-A peaks to protein-B's DB, however, DB is a region, so I just not sure if I should get the peaks in DB region and then do further overlap or distance calculation. I'm not sure if this is the correct practice.  

Thank you very much for you time and help!

**Comment by LTLA** [comment]
> Do you recommend to use both in one analysis? or one or another?

If you just want to get some overall numbers, you can just overlap all of the _csaw_ regions (DB or non-DB) with the peak calls. Then you can get numbers like the percentage of peaks that overlap any csaw region, and the percentage of peaks that overlap DB regions in either direction.

There are more formal approaches to integrating peak calls into _csaw_ - see the user's guide for details. However, these methods assume that the peak calling was done in a manner that is independent of DB, which is not the case for typical applications of peak callers. I would say that the same problem applies to anyone who is using peak calls as the input to a DB analysis.

> I just not sure if I should get the peaks in DB region and then do further overlap or distance calculation.

This makes sense to me.

**Comment by EllieDuan** [comment]
Great! Thanks a lot!!!
